changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Security
      labels:
        - security
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Internal
      labels:
        - chore
        - refactor
        - ci
        - dependencies
