import React, { useState } from 'react';
import { ArrowRight, Shield, UserPlus } from 'lucide-react';
import { useCreateIdentity } from '@/hooks/runtime/mutations';

interface RegisterScreenProps {
  onRegister: () => void;
  onSwitchToLogin: () => void;
}

export const RegisterScreen: React.FC<RegisterScreenProps> = ({ onRegister, onSwitchToLogin }) => {
  const [displayName, setDisplayName] = useState('');
  const [bio, setBio] = useState('');
  const [feedback, setFeedback] = useState<{ tone: 'error' | 'info'; message: string } | null>(null);
  const createMutation = useCreateIdentity();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFeedback(null);
    const name = displayName.trim();
    if (!name) {
      setFeedback({ tone: 'error', message: 'A display name is required to create your identity.' });
      return;
    }
    try {
      await createMutation.mutateAsync({ displayName: name, bio: bio.trim() || undefined });
      onRegister();
    } catch (error) {
      setFeedback({ tone: 'error', message: error instanceof Error ? error.message : 'Failed to create identity.' });
    }
  };

  return (
    <div className="fixed inset-0 z-[200] bg-bg-0 flex items-center justify-center overflow-auto">
      <div className="absolute inset-0 bg-gradient-to-b from-bg-0 via-bg-2 to-bg-0" />
      <div className="absolute inset-0" style={{ background: 'radial-gradient(circle at 50% 0%, rgba(19,221,236,0.08) 0%, transparent 60%)' }} />
      <div className="absolute inset-0 grid-overlay opacity-30" />

      <div className="relative z-10 w-full max-w-[440px] mx-6 my-10">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-r2 bg-primary/10 border border-primary/20 mb-4 shadow-glow">
            <Shield size={24} className="text-primary" />
          </div>
          <h1 className="text-display-l font-bold text-text-primary font-display tracking-tight">CREATE NODE</h1>
          <p className="micro-label text-text-tertiary mt-2">INITIALIZE // IDENTITY // PROTOCOL</p>
        </div>

        <form noValidate onSubmit={handleSubmit} className="glass-card rounded-r3 p-8 border border-stroke space-y-5">
          <div className="text-center mb-2">
            <h2 className="text-title font-semibold text-text-primary">NEW // IDENTITY</h2>
            <p className="text-caption text-text-tertiary mt-1">
              A new cryptographic identity will be generated by your local xorein runtime.
            </p>
          </div>

          {feedback && (
            <div
              role="alert"
              className={`rounded-r2 border px-4 py-3 text-caption ${feedback.tone === 'error' ? 'border-accent-danger/30 bg-accent-danger/10 text-accent-danger' : 'border-primary/30 bg-primary/10 text-primary'}`}
            >
              {feedback.message}
            </div>
          )}

          <div className="space-y-1.5">
            <label className="micro-label text-text-tertiary">DISPLAY NAME</label>
            <input
              type="text"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="neo_runner"
              maxLength={64}
              className="w-full h-14 px-5 rounded-full bg-surface-dark border border-stroke-subtle text-text-primary text-body placeholder:text-text-disabled focus:border-stroke-primary focus:outline-none transition-colors"
            />
          </div>

          <div className="space-y-1.5">
            <label className="micro-label text-text-tertiary">BIO <span className="text-text-disabled">(OPTIONAL)</span></label>
            <textarea
              value={bio}
              onChange={(e) => setBio(e.target.value)}
              rows={3}
              placeholder="A short description about yourself…"
              maxLength={200}
              className="w-full px-5 py-3 rounded-r2 bg-surface-dark border border-stroke-subtle text-text-primary text-body placeholder:text-text-disabled focus:border-stroke-primary focus:outline-none transition-colors resize-none"
            />
          </div>

          <button
            type="submit"
            disabled={createMutation.isPending}
            className="w-full h-14 rounded-full bg-primary text-bg-0 font-bold text-body-strong flex items-center justify-center gap-2 hover:shadow-glow transition-all disabled:opacity-40 mt-2"
          >
            {createMutation.isPending ? (
              <div className="w-5 h-5 border-2 border-bg-0/30 border-t-bg-0 rounded-full animate-spin" />
            ) : (
              <>
                <UserPlus size={18} />
                INITIALIZE NODE
                <ArrowRight size={18} />
              </>
            )}
          </button>

          <p className="text-center text-caption text-text-tertiary mt-3">
            Already have a backup?{' '}
            <button type="button" onClick={onSwitchToLogin} className="text-primary hover:underline font-semibold">
              Restore identity
            </button>
          </p>
        </form>
      </div>
    </div>
  );
};
